# Generated by Django 5.2.5 on 2025-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
