# Generated by Django 5.2.5 on 2026-03-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
